name: docker_build_server

on:
  workflow_dispatch:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # prod 
      - name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: /
          push: true
          tags: |
            cityofcapetown/bootstrap-email-smtp-server
